# Welcome to Jekyll!

# Website settings
title: "林承翰的個人網頁"
description: "Echo's blog,use Jekyll and github pages."
keywords: "chlin62,Echo,Cheng Han,blog,Cheng Han, Lin,Jekyll,github,gh-pages"

baseurl: "/"
url: "http://chlin62.github.io"
# url: "http://127.0.0.1:4000"

# blog img path
img_path: 'http://chlin62.github.io/static/img/blog'

# author
author:
  name: 'Echo'
  first_name: 'Cheng Han'
  last_name: 'Lin'
  email: 'chlin62@outlook.com'
  facebook_username: 'chenghan.lin62'
  github_username: 'chlin62'
  head_img: 'static/img/landing/chlin.jpg'

# social link
chlin:
  first_name: 'Cheng Han'
  last_name: 'Lin'
  description: '國立交通大學資訊管理研究所'
  link: 'https://www.facebook.com/chenghan.lin62'
  email: 'chlin62@outlook.com'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  link: 'Link'

# my projects
project:
  saplatform:
    name: 'Saplatform'
    url: '/Jack614/saplatform'
    img: 'static/img/landing/saplatform.png'
  jalpc:
    name: 'Jalpc'
    url: '/Jack614/jalpc_jekyll_theme'
    img: 'static/img/landing/jekyll.png'
  angularjs:
    name: 'Jalpc-A'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/angularjs.png'
  Rsser:
    name: 'Rsser'
    url: '/Jack614/Rsser'
    img: 'static/img/landing/rsser.png'

# blog index
index:
  home: 'Home'
  ip : '影像處理'
  cloud: '雲端技術'
  life: 'Life'


# donate
donate:
  wechat: 'static/img/landing/chlin.jpg'
  alipay: 'static/img/landing/chlin.jpg'

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 

# google analytics
ga:
  id: UA-82833700-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
